import React, { useState } from 'react';
import { X, Copy, Check, Download, Save, Terminal, Code, FileJson, FileCode } from 'lucide-react';
import { motion } from 'motion/react';
import { ScanResult, ExportConfig } from '../types';

interface CodeExporterProps {
  results: ScanResult[];
  onClose: () => void;
  config: ExportConfig;
  onConfigChange: (config: ExportConfig) => void;
}

export default function CodeExporter({ results, onClose, config, onConfigChange }: CodeExporterProps) {
  const [copied, setCopied] = useState(false);

  const formatName = (text: string) => {
    let name = text.replace(/[^a-zA-Z0-9]/g, '_');
    if (config.namingConvention === 'camelCase') {
      name = name.toLowerCase().replace(/(_[a-z])/g, (group) => group.toUpperCase().replace('_', ''));
    } else if (config.namingConvention === 'PascalCase') {
      name = name.toLowerCase().replace(/((^|_)[a-z])/g, (group) => group.toUpperCase().replace('_', ''));
    } else if (config.namingConvention === 'snake_case') {
      name = name.toLowerCase();
    }
    return config.prefix + name;
  };

  const generateCode = () => {
    const lines: string[] = [];
    
    if (config.format === 'cpp') {
      lines.push('// Generated by OneCore Offset Finder');
      lines.push('#pragma once');
      lines.push('#include <cstdint>');
      lines.push('');
      lines.push('namespace Offsets {');
      results.forEach(res => {
        if (config.includeComments && res.hints?.length) {
          lines.push(`    // ${res.hints.join(', ')}`);
        }
        lines.push(`    constexpr uintptr_t ${formatName(res.text)} = ${res.hexOffset};`);
      });
      lines.push('}');
    } else if (config.format === 'cs') {
      lines.push('// Generated by OneCore Offset Finder');
      lines.push('using System;');
      lines.push('');
      lines.push('public static class Offsets {');
      results.forEach(res => {
        if (config.includeComments && res.hints?.length) {
          lines.push(`    // ${res.hints.join(', ')}`);
        }
        lines.push(`    public const long ${formatName(res.text)} = ${res.hexOffset};`);
      });
      lines.push('}');
    } else if (config.format === 'ct') {
      lines.push('<?xml version="1.0" encoding="utf-8"?>');
      lines.push('<CheatTable CheatEngineTableVersion="42">');
      lines.push('  <CheatEntries>');
      results.forEach(res => {
        lines.push('    <CheatEntry>');
        lines.push(`      <Description>"${res.text}"</Description>`);
        lines.push(`      <Address>"libUE4.so"+${res.hexOffset.replace('0x', '')}</Address>`);
        lines.push('      <ShowAsHex>1</ShowAsHex>');
        lines.push('      <VariableType>4 Bytes</VariableType>');
        lines.push('    </CheatEntry>');
      });
      lines.push('  </CheatEntries>');
      lines.push('</CheatTable>');
    } else if (config.format === 'json') {
      return JSON.stringify(results.map(r => ({ name: r.text, offset: r.hexOffset })), null, 2);
    }

    return lines.join('\n');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = config.format === 'cpp' ? 'h' : config.format === 'cs' ? 'cs' : config.format === 'ct' ? 'ct' : 'json';
    const blob = new Blob([generateCode()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `offsets.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-0 sm:p-4 bg-black/80 backdrop-blur-sm"
    >
      <div className="w-full h-full sm:h-auto sm:max-h-[90vh] max-w-4xl bg-[#0a0a0a] border-0 sm:border border-[#00ff00]/30 rounded-none sm:rounded-xl overflow-hidden flex flex-col">
        <div className="p-4 pt-[calc(1rem+env(safe-area-inset-top))] sm:pt-4 border-b border-[#00ff00]/20 flex items-center justify-between bg-[#00ff00]/5">
          <div className="flex items-center gap-2">
            <Code className="w-5 h-5 text-[#00ff00]" />
            <h2 className="text-lg font-bold text-[#00ff00] uppercase tracking-wider">Code Exporter</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-[#00ff00]/10 rounded-lg transition-colors min-h-[44px] min-w-[44px] flex items-center justify-center">
            <X className="w-5 h-5 text-[#00ff00]" />
          </button>
        </div>

        <div className="flex-1 overflow-hidden flex flex-col sm:flex-row">
          {/* Settings Sidebar */}
          <div className="w-full sm:w-64 p-4 border-b sm:border-b-0 sm:border-r border-[#00ff00]/10 bg-black/40 space-y-4 sm:space-y-6 overflow-y-auto">
            <div>
              <label className="text-[10px] sm:text-xs text-[#00ff00]/60 uppercase font-bold mb-2 block">Format</label>
              <div className="grid grid-cols-2 gap-2">
                {[
                  { id: 'cpp', label: 'C++', icon: Code },
                  { id: 'cs', label: 'C#', icon: Terminal },
                  { id: 'ct', label: 'Cheat Engine', icon: FileCode },
                  { id: 'json', label: 'JSON', icon: FileJson },
                ].map(f => (
                  <button
                    key={f.id}
                    onClick={() => onConfigChange({ ...config, format: f.id as any })}
                    className={`p-2 rounded border flex flex-col items-center gap-1 transition-all min-h-[50px] justify-center ${
                      config.format === f.id 
                        ? 'bg-[#00ff00]/20 border-[#00ff00] text-[#00ff00]' 
                        : 'bg-black/40 border-[#00ff00]/20 text-[#00ff00]/40 hover:border-[#00ff00]/50'
                    }`}
                  >
                    <f.icon className="w-4 h-4" />
                    <span className="text-[9px] sm:text-[10px] font-bold uppercase">{f.label}</span>
                  </button>
                ))}
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-1 gap-4 sm:gap-6">
              <div>
                <label className="text-[10px] sm:text-xs text-[#00ff00]/60 uppercase font-bold mb-2 block">Naming</label>
                <select
                  value={config.namingConvention}
                  onChange={(e) => onConfigChange({ ...config, namingConvention: e.target.value as any })}
                  className="w-full bg-black/60 border border-[#00ff00]/20 rounded p-2 h-10 text-xs text-[#00ff00] focus:outline-none focus:border-[#00ff00]"
                >
                  <option value="snake_case">snake_case</option>
                  <option value="camelCase">camelCase</option>
                  <option value="PascalCase">PascalCase</option>
                </select>
              </div>

              <div>
                <label className="text-[10px] sm:text-xs text-[#00ff00]/60 uppercase font-bold mb-2 block">Prefix</label>
                <input
                  type="text"
                  value={config.prefix}
                  onChange={(e) => onConfigChange({ ...config, prefix: e.target.value })}
                  className="w-full bg-black/60 border border-[#00ff00]/20 rounded p-2 h-10 text-xs text-[#00ff00] focus:outline-none focus:border-[#00ff00]"
                  placeholder="e.g. OFFSET_"
                />
              </div>
            </div>

            <div className="flex items-center gap-2 py-2">
              <input
                type="checkbox"
                id="includeComments"
                checked={config.includeComments}
                onChange={(e) => onConfigChange({ ...config, includeComments: e.target.checked })}
                className="accent-[#00ff00] w-4 h-4"
              />
              <label htmlFor="includeComments" className="text-xs text-[#00ff00] cursor-pointer select-none">Include Comments</label>
            </div>
          </div>

          {/* Code Preview */}
          <div className="flex-1 flex flex-col bg-black overflow-hidden">
            <div className="p-2 bg-[#00ff00]/5 border-b border-[#00ff00]/10 flex justify-between items-center">
              <span className="text-[9px] sm:text-[10px] font-mono text-[#00ff00]/40 uppercase px-2">Preview ({results.length} items)</span>
              <div className="flex gap-2">
                <button 
                  onClick={handleCopy}
                  className="flex items-center gap-1 px-3 py-1.5 bg-[#00ff00]/10 hover:bg-[#00ff00]/20 text-[#00ff00] rounded text-[10px] font-bold uppercase transition-all min-h-[32px]"
                >
                  {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button 
                  onClick={handleDownload}
                  className="flex items-center gap-1 px-3 py-1.5 bg-[#00ff00] text-black hover:bg-[#00ff00]/80 rounded text-[10px] font-bold uppercase transition-all min-h-[32px]"
                >
                  <Download className="w-3 h-3" />
                  Download
                </button>
              </div>
            </div>
            <pre className="flex-1 p-4 overflow-auto font-mono text-[10px] sm:text-xs text-[#00ff00]/80 leading-relaxed scrollbar-thin scrollbar-thumb-[#00ff00]/20 pb-[calc(1rem+env(safe-area-inset-bottom))]">
              {generateCode()}
            </pre>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
